### ISSUE TITLE
CPU and RAM going crazy with Socket.IO

### ISSUE THREAD

**Issue by strblr** [n1ru4l/graphql-live-query#1006]
Hey @n1ru4l, hope you're doing well.

In one of my projects, we have an issue in production using this library, as the CPU sometimes spikes to 100% and the app is unusable. We put on a profiler, which shows the following:

![pyroscope-flames](https://github.com/n1ru4l/graphql-live-query/assets/30187797/7cf76adb-07e6-438a-bb2d-4a737d27bde4)

![image_2023_05_24T21_28_47_857Z](https://github.com/n1ru4l/graphql-live-query/assets/30187797/62bd0fbd-930f-433c-be72-697b6b899e63)

Looks like Socket.IO is having some troubles.
There is the possibility that this is unrelated to this library of course, but in case you're familiar with this or have the slightest idea where it might come from, I'm curious to hear about it.
I'm going to try ws instead of Socket.IO tomorrow.

**Comment by n1ru4l** [comment]
Hmm, I think this is most likely an issue on the Socket.IO end. I have not encountered this, I am also not using this in a large-scale deployment.

**Comment by strblr** [comment]
Turns out the problem was a combination of using json diff and having massive payloads. I removed the diffing and reduced payloads in size, now it's smooth. I also switched from Socket.IO to ws but this didn't make a difference. I'm posting this in case someone runs in a similar situation.
