### ISSUE TITLE
How to use with Redis?

### ISSUE THREAD

**Issue by danbeneventano** [n1ru4l/graphql-live-query#523]
The readme says:
> For scaling horizontally the independent InMemoryLiveQueryStore instances could be wired together via a PubSub system such as Redis.

Could you give an example for how to do this?

**Comment by n1ru4l** [comment]
You can create a Redis PubSub topic to which you emit the invalidated resources. On the single application instances you subscribe to these topics and invoke the local InMemoryLiveQueryStore.invalidate.

````
redis.subscribe("LIVE_QUERY_INVALIDATIONS", resourceIdentifier => {
  inMemorLiveQueryStore.invalidate(resourceIdentifier)
})

redis.publish("LIVE_QUERY_INVALIDATIONS", "Post:2")
````

**Comment by danbeneventano** [comment]
> You can create a Redis PubSub topic to which you emit the invalidated resources. On the single application instances you subscribe to these topics and invoke the local InMemoryLiveQueryStore.invalidate.
> 
> Pseudo Code:
> 
> ```ts
> redis.subscribe("LIVE_QUERY_INVALIDATIONS", resourceIdentifier => {
>   inMemorLiveQueryStore.invalidate(resourceIdentifier);
> });
> 
> redis.publish("LIVE_QUERY_INVALIDATIONS", "Post:2");
> ```

Thanks, simpler than I expected! Would you consider adding a `RedisLiveQueryStore` that takes care of this automatically?

**Comment by n1ru4l** [comment]
I tried to avoid it for now. There are both `ioredis` and `redis` which are heavily used. Which one should the implementation support? Both? Only one?

Also, note that this approach is not a true `RedisLiveQueryStore` approach. The resource identifiers are still stored within memory, not Redis, we basically only have a bridge that boradcasts invalidations to all connected InMemorLiveQueryStore instances.

If this should be a seperate package it should probably be an API like `const bridgedLiveQueryStore = withRedisBridge(inMemoryLiveQueryStore)`.

A true `RedisLiveQueryStore` would probably store all the information's about the subscribed resources in Redis.

**Comment by n1ru4l** [comment]
@danbeneventano You created a great example over here: https://github.com/joincomet/comet/blob/1aa96e23cb85d61562c5674489987168aa0a7b8a/server/src/util/RedisLiveQueryStore.ts#L1-L59

Maybe we should add it as an recipe to the readme over here? https://github.com/n1ru4l/graphql-live-query/tree/main/packages/in-memory-live-query-store

**Comment by danbeneventano** [comment]
@n1ru4l sure thing, I created a PR

**Comment by notrab** [comment]
@avesoceans I appreciate it's been a while but I'm on a quest to teach others how to use Redis with Live Queries. I noticed in your example it's mostly using Redis for invalidation but not the actual storage of values, or is that incorrect?

Would you be interested in collaborating on this further?
