### ISSUE TITLE
`iterator.return` running when it's not supposed to.

### ISSUE THREAD

**Issue by TrentWest7190** [n1ru4l/graphql-live-query#526]
Hi, I'm currently having a very strange problem. I'm having differing execution results for the same server implementation of the live query with different clients. Specifically, a difference between a production and development version of my client code. On the development version, everything works just fine 100% of the time. However, on my production code, there is a pattern of live query results not being sent back to the client. After throwing in a lot of debugging statements, the only difference between the execution of the two requests that I can find, is that on my production version of the client, this function is being run and it's releasing the identifiers used to alert of a change, even though it should still be watching those identifiers.

https://github.com/n1ru4l/graphql-live-query/blob/f6d3a868e60715fd69ede08247162bb962767f13/packages/in-memory-live-query-store/src/InMemoryLiveQueryStore.ts#L354-L359

I'm really stumped on this one, since both clients should be sending identical requests, and I could not find anything in this codebase which would change upon setting the environment to production rather than development.

**Comment by TrentWest7190** [comment]
Sorry, upon further inspection, this does not seem to be an issue with this library, but in fact an issue with how this library interacts with `graphql-ws`, for some reason, when the live query attempts to send its update, the socket is closing before it gets a chance to respond. I will investigate further.

**Comment by TrentWest7190** [comment]
My issue ended up being completely unrelated to this library. Sorry for the confusion.

**Comment by n1ru4l** [comment]
@TrentWest7190 Hey, could you share what exactly was the issue? Is it related to any other dependency that you would use together with this library? Could we document this so other people will have an easier time resolving this issue?

**Comment by TrentWest7190** [comment]
Sure, though the issue was not directly related to the live queries, it did have to do with receiving data back from several graphql events at the same time, specifically through the `graphql-ws` implementation of the client. Basically, I was running a mutation which was updating a resource which a live query was watching. `graphql-ws`'s default behavior is to close the socket when it thinks there are no more subscriptions it needs to keep track of. The results from the mutation, and the new results from the live query were being sent nearly simultaneously, but the mutation was returning first. From what I gathered, the situation was the websocket was closing after receiving the mutation results due to the client somehow not holding onto the correct number of locks. No locks = connection gets closed. I fixed it by adding a `keepAlive` value to the `graphql-ws` client configuration, so that it would wait, see that it was still getting results from the live query, and know to persist the socket connection. So, in the end, not related to `graphql-live-query` really, just a note that if you're using `graphql-ws` with live queries, you may want to configure a `keepAlive` time so that it doesn't drop the connection prematurely.
