### ISSUE TITLE
Debouncing Support ?

### ISSUE THREAD

**Issue by ccollie** [n1ru4l/graphql-live-query#626]
Is there a possibility of adding a debounce strategy (with an upper limit) ? E.g. debounce changes for 50ms with a hard limit of 500ms. The diff would be between the value at the start of the debounce period (since thats the version matching the client) and the value at the end of the period. 

As a use case I'm building an api to a queueing engine, and certain queries can get chatty at high concurrency. Most of the values I'm monitoring are gauges/counters and other entities for which from a dashboard perspective intermediate values (within a certain granularity) are not important.

**Comment by n1ru4l** [comment]
I think the correct term is throtteling? I would accept a contribution for this 😇

**Comment by ccollie** [comment]
Not saying I'm committing to this :-), but where's a good place to start ?

**Comment by n1ru4l** [comment]
This is the function that could be debounced: https://github.com/n1ru4l/graphql-live-query/blob/3eca29866c8e7046bfd2f00c342dbb4a93e24693/packages/in-memory-live-query-store/src/InMemoryLiveQueryStore.ts#L269

**Comment by ccollie** [comment]
Hey @n1ru4l , could you have a quick look at https://github.com/ccollie/graphql-live-query/commit/929e67  to see if this is a viable direction?

Or should I just go ahead with a PR ?

BTW, I'm still figuring out the tests for `InMemoryLiveQueryStore`

**Comment by n1ru4l** [comment]
@ccollie Feel free to open a PR so I can comment on that and start the conversation!

**Comment by n1ru4l** [comment]
This is now published 😎

**Comment by ccollie** [comment]
@n1ru4l thanks for the followthrough. I've been knee-deep in projects the past month.
