### ISSUE TITLE
Issue with chalk dependency within jsondiffpatch [graphql-live-query-patch-jsondiffpatch]

### ISSUE THREAD

**Issue by TrentWest7190** [n1ru4l/graphql-live-query#638]
https://github.com/benjamine/jsondiffpatch/issues/249

https://github.com/n1ru4l/graphql-live-query/blob/868404fd564d0a2b32fc4a3533edffc1ba932101/packages/graphql-live-query-patch-json-diff/src/applyJSONDiffPatch.ts#L2

The issue is that the `@n1ru4l/graphql-live-query-patch-jsondiffpatch` package doesn't function in-browser due to importing everything from the jsondiffpatch package within this file, which makes the browser try to import the `chalk` dependency, which throws an error in the browser because it's trying to access `process` which doesn't exist outside of node.

**Comment by TrentWest7190** [comment]
It looks like the intended solution, from the `jsondiffpatch` readme is to import one of the distributions within the package for browser use:

https://github.com/benjamine/jsondiffpatch#browser



> ### browser
> In a browser, you could load directly a bundle in /dist, eg. /dist/jsondiffpatch.umd.js.

**Comment by n1ru4l** [comment]
Ah it is unfortunate that this package is pretty messy 😰 Maybe we should inline it here instead - and further tweak it to not include the previous result - only the addition

**Comment by dburles** [comment]
> Ah it is unfortunate that this package is pretty messy 😰 Maybe we should inline it here instead - and further tweak it to not include the previous result - only the addition

100% I was thinking the same thing

**Comment by n1ru4l** [comment]
@dburles @TrentWest7190 Contributions would be highly appreciated :)

**Comment by n1ru4l** [comment]
I finally created a slim version 🥳  https://github.com/n1ru4l/graphql-live-query/pull/692

**Comment by n1ru4l** [comment]
Closing this as the jsondiffpatch dependency got removed 🥳
