### ISSUE TITLE
Unsubscribe/dispose doesn’t work with applyLiveQueryJSONDiffPatchGenerator

### ISSUE THREAD

**Issue by ianberdin** [n1ru4l/graphql-live-query#851]
Only today I noticed that when using applyLiveQueryJSONDiffPatchGenerator, unsubscribing (dispose) to queries does not work. I.e. if you Invalidate(...), it will still send a patch to the client. However, everything works if you remove applyLiveQueryJSONDiffPatchGenerator.

1. [Code from example](https://github.com/n1ru4l/graphql-live-query/blob/1c751de86cb742040d8a602a14de398064b76832/packages/todo-example/server/src/index.ts#L54)
```javascript
const execute = flow(
    liveQueryStore.makeExecute(defaultExecute),
    applyLiveQueryJSONPatchGenerator
);
```

2. [Code from readme](https://github.com/n1ru4l/graphql-live-query/blob/7e56721b66d165c0373152411d6e9b3f2f16b59d/packages/graphql-live-query-patch-json-diff/README.md#applylivequeryjsondiffpatchgenerator)
```javascript
const result = applyLiveQueryJSONDiffPatchGenerator(
  execute(...)
);
```

An example: the last message is a patch After unsubscribe.
![image](https://user-images.githubusercontent.com/2521933/147300921-c49d5140-ff6e-4d5e-ab02-a0c243488455.png)

Node: v16.13.1
Chrome: v96
graphql-ws: 5.5.5
@urql/core: 2.3.6
@n1ru4l/graphql-live-query: 0.9.0
@n1ru4l/graphql-live-query-patch-jsondiffpatch: 0.7.0
@n1ru4l/in-memory-live-query-store: 0.8.0

**Comment by n1ru4l** [comment]
I will get to this soon, the AsyncIterable cleanup is not properly proxied

**Comment by n1ru4l** [comment]
@ianberdin COuld you please confirm whether this is resolved with the following versions: https://github.com/n1ru4l/graphql-live-query/pull/850#issuecomment-999233472

**Comment by ianberdin** [comment]
@n1ru4l  It perfectly works, thanks a lot!
